import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const lib = resolve(root, 'lib')
const [rawCss, rawClientBody] = await Promise.all([
  readFile(resolve(root, 'src/client/theme.css'), 'utf8'),
  readFile(resolve(root, 'src/client/index.js'), 'utf8'),
])
const css = rawCss.replace(/\r\n?/g, '\n')
const clientBody = rawClientBody.replace(/\r\n?/g, '\n')

await mkdir(lib, { recursive: true })
await copyFile(resolve(root, 'src/index.js'), resolve(lib, 'index.js'))

const bundle = [
  '// Generated by scripts/build.mjs. Edit src/client/* instead.',
  'window.__ModuleLoader__.load({',
  '  id: "dsh-plugin-gouden-leeuw-theme",',
  '  factory: (require) => {',
  '    var module = { exports: {} };',
  '    var exports = module.exports;',
  `    const THEME_CSS = ${JSON.stringify(css)};`,
  clientBody,
  '    return module.exports;',
  '  },',
  '});',
  '',
].join('\n')

await writeFile(resolve(lib, 'client.js'), bundle, 'utf8')
